apiVersion: v1
kind: ConfigMap
metadata:
  name: javascript-eks-app-01-configmap
  namespace: cicd-test-env-01
data:
  db.properties: |-
    {
      "database": {
        "db_user": "dev-username",
        "db_password": "dev-password"
      }
    }
