apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-eks-app-01-cfgstore-deployment
  namespace: cicd-test-env-01
  labels:
    app: javascript-eks-app-01-cfgstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-eks-app-01-cfgstore
  template:
    metadata:
      labels:
        app: javascript-eks-app-01-cfgstore
    spec:
      containers:
        - name: javascript-eks-app-01-cfgstore
          image: 521651615177.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-dev-cicd-test-env-01-javascript-eks-app-01:6d82ee7a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: '/app/config/default.json'
              subPath: 'default.json'
          envFrom:
            - secretRef:
                name: app-secret
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: javascript-eks-app-01-configmap
            items:
              - key: 'app.properties'
                path: 'default.json'
