apiVersion: v1
kind: Service
metadata:
  name: javascript-eks-app-01-cfgstore-service
  namespace: cicd-test-env-01
  labels:
    app: javascript-eks-app-01-cfgstore
spec:
  selector:
    app: javascript-eks-app-01-cfgstore
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
